on:
  push:
    branches:
      - master

jobs:
  upload_to_sftp:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate DutyLogs-Script.zip
        run: zip -r DutyLogs-Script.zip script

      - name: Upload DutyLogs-Script Artifact
        uses: actions/upload-artifact@v1
        with:
          name: DutyLogs-Script.zip
          path: DutyLogs-Script.zip

      - name: Remove script directory
        run: rm -r script

      - name: Generate DutyLogs-Bot.zip
        run: zip -r DutyLogs-Bot.zip .

      - name: Upload DutyLogs-Bot Artifact
        uses: actions/upload-artifact@v1
        with:
          name: DutyLogs-Bot.zip
          path: DutyLogs-Bot.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: release-${{ github.run_number }}-${{ github.run_id }}
          release_name: Latest
          body: Automated release
          draft: false
          prerelease: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Release Artifacts
          path: |
            DutyLogs-Script.zip
            DutyLogs-Bot.zip

      - name: Attach Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: DutyLogs-Script.zip
          asset_name: DutyLogs-Script.zip
          asset_content_type: application/zip

      - name: Attach Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: DutyLogs-Bot.zip
          asset_name: DutyLogs-Bot.zip
          asset_content_type: application/zip
